DELIMITER //
DROP TRIGGER IF EXISTS BU_TIPOUSUARIO;
CREATE TRIGGER BU_TIPOUSUARIO
BEFORE UPDATE ON tipo_usuario FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_USUARIO;
CREATE TRIGGER BU_USUARIO
BEFORE UPDATE ON usuario FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_TELEFONO;
CREATE TRIGGER BU_TELEFONO
BEFORE UPDATE ON telefono FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_PERSONA;
CREATE TRIGGER BU_PERSONA
BEFORE UPDATE ON persona FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //


DROP TRIGGER IF EXISTS BU_PAJXPER;
CREATE TRIGGER BU_PAJXPER
BEFORE UPDATE ON pajaro_x_persona FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CORREO;
CREATE TRIGGER BU_CORREO
BEFORE UPDATE ON correo FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATZONAVIDA;
CREATE TRIGGER BU_CATZONAVIDA
BEFORE UPDATE ON catalogo_zona_vida FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATTIPOPICO;
CREATE TRIGGER BU_CATTIPOPICO
BEFORE UPDATE ON catalogo_tipo_pico FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATSUBORDEN;
CREATE TRIGGER BU_CATSUBORDEN
BEFORE UPDATE ON catalogo_suborden FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATORDEN;
CREATE TRIGGER BU_CATORDEN
BEFORE UPDATE ON catalogo_orden FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATGENERO;
CREATE TRIGGER BU_CATGENERO
BEFORE UPDATE ON catalogo_genero FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATFAMILIA;
CREATE TRIGGER BU_CATFAMILIA
BEFORE UPDATE ON catalogo_familia FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATESPECIE;
CREATE TRIGGER BU_CATESPECIE
BEFORE UPDATE ON catalogo_especie FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATCOLOR;
CREATE TRIGGER BU_CATCOLOR
BEFORE UPDATE ON catalogo_color FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATCLASE;
CREATE TRIGGER BU_CATCLASE
BEFORE UPDATE ON catalogo_clase FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BU_CATCANTHUEVOS;
CREATE TRIGGER BU_CATCANTHUEVOS
BEFORE UPDATE ON catalogo_cantidad_huevos FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //
