DELIMITER //
DROP TRIGGER IF EXISTS BI_TIPOUSUARIO;
CREATE TRIGGER BI_TIPOUSUARIO
BEFORE INSERT ON tipo_usuario FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_USUARIO;
CREATE TRIGGER BI_USUARIO
BEFORE INSERT ON usuario FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_TELEFONO;
CREATE TRIGGER BI_TELEFONO
BEFORE INSERT ON telefono FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_PERSONA;
CREATE TRIGGER BI_PERSONA
BEFORE INSERT ON persona FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_PAJXPER;
CREATE TRIGGER BI_PAJXPER
BEFORE INSERT ON pajaro_x_persona FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CORREO;
CREATE TRIGGER BI_CORREO
BEFORE INSERT ON correo FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATZONAVIDA;
CREATE TRIGGER BI_CATZONAVIDA
BEFORE INSERT ON catalogo_zona_vida FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATTIPOPICO;
CREATE TRIGGER BI_CATTIPOPICO
BEFORE INSERT ON catalogo_tipo_pico FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATSUBORDEN;
CREATE TRIGGER BI_CATSUBORDEN
BEFORE INSERT ON catalogo_suborden FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATORDEN;
CREATE TRIGGER BI_CATORDEN
BEFORE INSERT ON catalogo_orden FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATGENERO;
CREATE TRIGGER BI_CATGENERO
BEFORE INSERT ON catalogo_genero FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATFAMILIA;
CREATE TRIGGER BI_CATFAMILIA
BEFORE INSERT ON catalogo_familia FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATESPECIE;
CREATE TRIGGER BI_CATESPECIE
BEFORE INSERT ON catalogo_especie FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATCOLOR;
CREATE TRIGGER BI_CATCOLOR
BEFORE INSERT ON catalogo_color FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATCLASE;
CREATE TRIGGER BI_CATCLASE
BEFORE INSERT ON catalogo_clase FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //

DROP TRIGGER IF EXISTS BI_CATCANTHUEVOS;
CREATE TRIGGER BI_CATCANTHUEVOS
BEFORE INSERT ON catalogo_cantidad_huevos FOR EACH ROW 
BEGIN 
  SET NEW.USUARIO_CREACION := CURRENT_USER;
  SET NEW.USUARIO_MODIFICACION := CURRENT_USER;
  SET NEW.FECHA_CREACION := CURDATE();
  SET NEW.FECHA_MODIFICACION := CURDATE();
END //
