DELIMITER //
CREATE FUNCTION `insertar_ave`(`ID_PERSONA` INT, `CEDULA` INT, `ESPECIE_ID` INT, `CANT_HUEVOS_MENOR` INT, `CANT_HUEVOS_MAYOR` INT)
	RETURNS INT
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	INSERT INTO pajaro_x_persona (CEDULA, persona_ID, catalogo_especie_ID,catalogo_cantidad_huevos_ID_menor,catalogo_cantidad_huevos_ID_mayor) VALUES (`CEDULA`,`ID_PERSONA`,`ESPECIE_ID`, `CANT_HUEVOS_MENOR`, `CANT_HUEVOS_MAYOR`);
	SET @last_id = LAST_INSERT_ID(); 
	RETURN @last_id;
END //