DELIMITER //
CREATE PROCEDURE `insertar_pico`(IN `ID_PAJARO` INT, IN `ID_PICO` INT)
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	INSERT INTO PICOS_X_PAJARO (pajaro_x_persona_ID, catalogo_tipo_pico_ID) values (`ID_PAJARO`,`ID_PICO`);
	commit;
END //