DELIMITER //
CREATE PROCEDURE `insertar_color`(IN `ID_PAJARO` INT, IN `ID_COLOR` INT)
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	INSERT INTO COLORES_X_PAJARO (pajaro_x_persona_ID, catalogo_color_ID) values (`ID_PAJARO`,`ID_COLOR`);
	commit;
END //