DELIMITER //
CREATE DEFINER=`WingWatch`@`localhost` PROCEDURE `insertar_imagenes`(IN `NOMBRE` TINYTEXT, IN `URL` TINYTEXT, IN `ID_PAJARO` INT)
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	INSERT INTO FOTOS (NOMBRE_FOTO,URL,PAJARO_X_PERSONA_ID) VALUES (`NOMBRE`,`URL`,`ID_PAJARO`);
	COMMIT;
END //