CREATE TABLE "USUARIOS" (
"CORREO" VARCHAR(60) NOT NULL,
"ENCRIPTACION" VARCHAR(200) NOT NULL,
"NOMBRE" VARCHAR(50) NOT NULL,
"APELLIDOS" VARCHAR(60) NOT NULL,
"TIPO_USUARIO" DECIMAL NOT NULL,
"ES_ADMINISTRADOR" DECIMAL NOT NULL,
"REGISTRO_FOTOS" DECIMAL NOT NULL,
"FECHA_CREACION" DATE NOT NULL,
"FECHA_MODIFICACION" DATE NOT NULL,
"USUARIO_CREACION" VARCHAR(20) NOT NULL,
"USUARIO_MODIFICACION" VARCHAR(20) NOT NULL,
PRIMARY KEY ("CORREO") 
);

CREATE TABLE "CATALOGO_TIPO_USUARIO" (
"ID_TIPO_USUARIO" DECIMAL NOT NULL,
"TIPO_USUARIO" VARCHAR(30) NOT NULL,
PRIMARY KEY ("ID_TIPO_USUARIO") 
);

CREATE TABLE "CATALOGO_AVES" (
"ID_AVE" DECIMAL NOT NULL,
"NOMBRE_CIENTIFICO" VARCHAR(100) NOT NULL,
"NOMBRE_COMUN" VARCHAR(100) NOT NULL,
"ORDEN" DECIMAL NOT NULL,
"SUBORDEN" DECIMAL NOT NULL,
"FAMILIA" DECIMAL NOT NULL,
"GENERO" DECIMAL NOT NULL,
"ESPECIE" DECIMAL NOT NULL,
"TAMANIO" DECIMAL NOT NULL,
"PICO" DECIMAL NOT NULL,
"COLOR" DECIMAL NOT NULL,
"CANT_HUEVOS" DECIMAL NOT NULL,
"UBICACION" DECIMAL NOT NULL,
PRIMARY KEY ("ID_AVE") 
);

CREATE TABLE "CATALOGO_ORDEN" (
"ID_ORDEN" DECIMAL NOT NULL,
"ORDEN" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_ORDEN") 
);

CREATE TABLE "CATALOGO_SUBORDEN" (
"ID_SUBORDEN" DECIMAL NOT NULL,
"SUBORDEN" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_SUBORDEN") 
);

CREATE TABLE "CATALOGO_FAMILIA" (
"ID_FAMILIA" DECIMAL NOT NULL,
"FAMILIA" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_FAMILIA") 
);

CREATE TABLE "CATALOGO_GENERO" (
"ID_GENERO" DECIMAL NOT NULL,
"GENERO" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_GENERO") 
);

CREATE TABLE "CATALOGO_ESPECIE" (
"ID_ESPECIE" DECIMAL NOT NULL,
"ESPECIE" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_ESPECIE") 
);

CREATE TABLE "CATALOGO_TAMANIO" (
"ID_TAMANIO" DECIMAL NOT NULL,
"TAMANIO" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_TAMANIO") 
);

CREATE TABLE "CATALOGO_PICO" (
"ID_PICO" DECIMAL NOT NULL,
"PICO" VARCHAR(50) NOT NULL,
PRIMARY KEY ("ID_PICO") 
);

CREATE TABLE "CATALOGO_COLOR" (
"ID_COLOR" DECIMAL NOT NULL,
"COLOR" CLOB NOT NULL,
PRIMARY KEY ("ID_COLOR") 
);

CREATE TABLE "CATALOGO_UBICACION" (
"ID_UBICACION" DECIMAL NOT NULL,
"UBICACION" CLOB NOT NULL,
PRIMARY KEY ("ID_UBICACION") 
);

CREATE TABLE "REGISTRO_AVISTAMIENTOS" (
"ID_REGISTRO" DECIMAL NOT NULL,
"FOTOS_PERTENECIENTES" DECIMAL NOT NULL,
PRIMARY KEY ("ID_REGISTRO") 
);

CREATE TABLE "FOTOS_Y_CLASIFICACION" (
"ID_FOTO" DECIMAL NOT NULL,
"CHEQUEO_ORNITOLOGO" VARCHAR(1) NULL,
"DIRECCION_FOTO" CLOB NOT NULL,
"AVE_ASOCIADA" DECIMAL NOT NULL,
PRIMARY KEY ("ID_FOTO") 
);

CREATE TABLE "FOTO_PERTENECE_REGISTRO" (
"ID_REGISTRO" DECIMAL NOT NULL,
"ID_FOTO" DECIMAL NOT NULL,
PRIMARY KEY ("ID_REGISTRO", "ID_FOTO") 
);

CREATE TABLE "CATALOGO_CORREOS" (
"ID_MENSAJE" DECIMAL NOT NULL,
"CUERPO" VARCHAR(255) NULL,
"ASUNTO" VARCHAR(255) NULL,
PRIMARY KEY ("ID_MENSAJE") 
);


ALTER TABLE "USUARIOS" ADD CONSTRAINT "fk_USUARIOS_CATALOGO_TIPO_USUARIO_1" FOREIGN KEY ("TIPO_USUARIO") REFERENCES "CATALOGO_TIPO_USUARIO" ("ID_TIPO_USUARIO");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_ORDEN_1" FOREIGN KEY ("ORDEN") REFERENCES "CATALOGO_ORDEN" ("ID_ORDEN");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_SUBORDEN_1" FOREIGN KEY ("SUBORDEN") REFERENCES "CATALOGO_SUBORDEN" ("ID_SUBORDEN");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_FAMILIA_1" FOREIGN KEY ("FAMILIA") REFERENCES "CATALOGO_FAMILIA" ("ID_FAMILIA");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_GENERO_1" FOREIGN KEY ("GENERO") REFERENCES "CATALOGO_GENERO" ("ID_GENERO");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_ESPECIE_1" FOREIGN KEY ("ESPECIE") REFERENCES "CATALOGO_ESPECIE" ("ID_ESPECIE");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_TAMANIO_1" FOREIGN KEY ("TAMANIO") REFERENCES "CATALOGO_TAMANIO" ("ID_TAMANIO");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_PICO_1" FOREIGN KEY ("PICO") REFERENCES "CATALOGO_PICO" ("ID_PICO");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_COLOR_1" FOREIGN KEY ("COLOR") REFERENCES "CATALOGO_COLOR" ("ID_COLOR");
ALTER TABLE "CATALOGO_AVES" ADD CONSTRAINT "fk_CATALOGO_AVES_CATALOGO_UBICACION_1" FOREIGN KEY ("UBICACION") REFERENCES "CATALOGO_UBICACION" ("ID_UBICACION");
ALTER TABLE "USUARIOS" ADD CONSTRAINT "fk_USUARIOS_REGISTRO_FOTOS_1" FOREIGN KEY ("REGISTRO_FOTOS") REFERENCES "REGISTRO_AVISTAMIENTOS" ("ID_REGISTRO");
ALTER TABLE "FOTO_PERTENECE_REGISTRO" ADD CONSTRAINT "fk_FOTO_PERTENECE_REGISTRO_REGISTRO_AVISTAMIENTOS_1" FOREIGN KEY ("ID_REGISTRO") REFERENCES "REGISTRO_AVISTAMIENTOS" ("ID_REGISTRO");
ALTER TABLE "FOTO_PERTENECE_REGISTRO" ADD CONSTRAINT "fk_FOTO_PERTENECE_REGISTRO_FOTOS_Y_CLASIFICACION_1" FOREIGN KEY ("ID_FOTO") REFERENCES "FOTOS_Y_CLASIFICACION" ("ID_FOTO");
ALTER TABLE "FOTOS_Y_CLASIFICACION" ADD CONSTRAINT "fk_FOTOS_Y_CLASIFICACION_CATALOGO_AVES_1" FOREIGN KEY ("AVE_ASOCIADA") REFERENCES "CATALOGO_AVES" ("ID_AVE");

